### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by hotrush** [tylim88/Firelordjs#51]
Hey, is it possible to paginate with the latest received item?

From firestore docs:

```
import { collection, query, orderBy, startAfter, limit, getDocs } from "firebase/firestore";  

// Query the first page of docs
const first = query(collection(db, "cities"), orderBy("population"), limit(25));
const documentSnapshots = await getDocs(first);

// Get the last visible document
const lastVisible = documentSnapshots.docs[documentSnapshots.docs.length-1];
console.log("last", lastVisible);

// Construct a new query starting at this document,
// get the next 25 cities.
const next = query(collection(db, "cities"),
    orderBy("population"),
    startAfter(lastVisible),
    limit(25));
```

**Comment by tylim88** [comment]
I see, there is a typing bug in it, working on it right now, please wait for v1.2

**Comment by tylim88** [comment]
ETA is today

**Comment by hotrush** [comment]
Nice

**Comment by tylim88** [comment]
fixed at commit https://github.com/tylim88/Firelordjs/commit/d668bb475c1f6e0d6f04c6f97d63eb10a7dc4ea9

v1.2.0 released

setup:
```ts
import { MetaTypeCreator } from 'firelordjs'
import { getFirelord } from 'firelordjs'
import { initializeApp } from 'firebase/app'
import { getFirestore } from 'firebase/firestore'

const app = initializeApp({
	apiKey: '### FIREBASE API KEY ###',
	authDomain: '### FIREBASE AUTH DOMAIN ###',
	projectId: '### CLOUD FIRESTORE PROJECT ID ###',
})

export type Cities = MetaTypeCreator<
	{
		population: number
		// other data type
	},
	'cities',
	string
>

const db = getFirestore()

const firelordExample = getFirelord<Cities>(db)
// OR
const firelordExample_Alt = getFirelord<Cities>()

export const cities = firelordExample('cities')
```

usage:
```ts
import { cities } from './someFile'
import {
	getDocs,
	query,
	orderBy,
	startAfter,
	limit,
} from 'firelordjs'

const pagination = async () => {
	const querySnapshot = await getDocs(
		query(cities.collection(), orderBy('population'), limit(25))
	)

	const lastVisible = querySnapshot.docs[querySnapshot.docs.length - 1]

	if (lastVisible) {
		const nextQuery = query(
			cities.collection(),
			orderBy('population'),
			startAfter(lastVisible),
			limit(25)
		)
	}
}
```

**Comment by tylim88** [comment]
it should be fine by now, let me know if you still having trouble using it

**Comment by hotrush** [comment]
So, it doesn't show type error anymore but still doesn't work.

My code is next:

```
      const items = await getDocs(
        query(
          domainsRef('domains').collection(),
          orderBy(this.sortBy, this.sortOrder),
          limit(this.limit)
        )
      );
      console.log(items.docs);

      const cursor = items.docs[items.docs.length - 1];
      console.log(cursor);
      console.log(cursor.constructor.name);

      const items2 = await getDocs(
        query(
          domainsRef('domains').collection(),
          orderBy(this.sortBy, this.sortOrder),
          startAfter(cursor),
          limit(this.limit)
        )
      );

      console.log(items2);
```

And in console I can see the next

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/1247004/166971896-fa5f443f-d7b0-4d5f-a15b-4793212c1e49.png">

I think that's some typescript compiling issue or misconfiguration, but have no idea how to fix it. Using firebase sdk directly it works.

**Comment by hotrush** [comment]
Let me know if you need any details from me

**Comment by tylim88** [comment]
while I am adding more tests, can you try this quick fix?

```bash
npm i firelordjs@1.2.1-beta.1
```
or 
```bash
npm i firelordjs@beta
```

**Comment by tylim88** [comment]
fixed at https://github.com/tylim88/Firelordjs/commit/1f59fd8db168ca72af19bbb24a9a3a6d8a67e770

I am confident this will do it, tested against firestore(not emulator) https://github.com/tylim88/Firelordjs/commit/1f59fd8db168ca72af19bbb24a9a3a6d8a67e770#diff-8ee26c0c425b969c55514487ca5b617d12c9e4abf695508b12e9843c3996db20

**Comment by hotrush** [comment]
Yes, it works now, thanks a lot 👍
